---
  - name: Setting ubuntu
    hosts: all
    become: true 
    tasks:
      - name:  Install nano package
        apt:
          name: nano
          state: present

      - name: Install fish package
        apt:
          name: fish
          state: present
        tags:
          - fish

      - name: Install tree package
        apt:
          name: tree
          state: present
        tags:
            - tree

      - name: Set timezone to UTC
        timezone:
          name: UTC
        tags:
          - timezone

      - name: Install htop
        apt:
          name: htop
          state: present
        tags:
          - monitoring