---
  - name: Setting ubuntu
    hosts: all
    become: true 
    tasks:
      - name:  Install required dependencies
        apt:
          name:
            - nano
            - fish
            - tree
            - htop
            - apt-transport-https
            - ca-certificates
            - curl
            - software-properties-common
          state: present

      - name: Set timezone to UTC
        timezone:
          name: UTC
        tags:
          - timezone

      - name: Install pip for Python 3
        package:
          name: python3-pip
          state: present

      - name: Install requests Python package
        pip:
          name: requests
          state: present

      - name: Update apt cache
        apt:
          update_cache: yes