---
  - name: Setting ubuntu
    hosts: all
    become: true 
    tasks:
      - name: Create a user with sudo privileges
        user:
          name: newuser
          state: present
          shell: /bin/bash
        tags:
          - user

      - name: Add user to sudo group
        user:
          name: newuser
          groups: sudo
          append: yes
        tags:
          - user
